--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FP_PLAYKIND
--------------------------------------------------------

  CREATE TABLE "MOVIE"."FP_PLAYKIND" 
   (	"NUM" NUMBER(10,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MOVIE.FP_PLAYKIND
SET DEFINE OFF;
Insert into MOVIE.FP_PLAYKIND (NUM,NAME) values (1,'2D');
Insert into MOVIE.FP_PLAYKIND (NUM,NAME) values (2,'3D');
Insert into MOVIE.FP_PLAYKIND (NUM,NAME) values (3,'2D(자막)');
Insert into MOVIE.FP_PLAYKIND (NUM,NAME) values (4,'3D(자막)');
--------------------------------------------------------
--  DDL for Index PK_FP_playKind_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOVIE"."PK_FP_playKind_NUM" ON "MOVIE"."FP_PLAYKIND" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FP_PLAYKIND
--------------------------------------------------------

  ALTER TABLE "MOVIE"."FP_PLAYKIND" ADD CONSTRAINT "PK_FP_playKind_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOVIE"."FP_PLAYKIND" MODIFY ("NUM" NOT NULL ENABLE);
